### ISSUE TITLE
Know what children fields are wanted

### ISSUE THREAD

**Issue by mathieutu** [glesys/butler-graphql#32]
Hi, 
I'm digging in your package and making some tests.

I would like to know in a resolver what fields are wanted in the resolved type, to be able to use them in a select.

example: 
```gql
{
  users {
    id,
    firstName
    lastName
  }
}
```

```php
class Users implements QueryInterface
{
    public function __invoke($root, array $args, array $context, ResolveInfo $info)
    {
        return User::all(/* [id, firstName, lastName] */);
    }
}
```

Could we do that?

Thanks.

**Comment by wecc** [comment]
Hi!

The simplest way would be to use `$info->getFieldSelection()` (you can specify the depth, 0 by default) to inspect what fields are present in the query.

You could also inspect something like `$info->fieldNodes[0]->selectionSet->selections[*]` if you really want to inspect field arguments, definitions and more.

Let me know if this helps!

**Comment by mathieutu** [comment]
Hi!
Thanks for this really quick answer, I was just closing the issue saying "nvm, I found getFieldSelection method." 😅

I let you know if I need something else, thanks!
